/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author jjott
 */
public class AnimaisGUI extends javax.swing.JFrame {

    /**
     * Creates new form Animais
     */
    public AnimaisGUI() {
        initComponents();
        this.setVisible(true);
        this.setSize(400, 400);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
        this.setTitle("Animais");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeAnimalTxt = new javax.swing.JTextField();
        racaAnimalTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        especieAnimalTxt = new javax.swing.JTextField();
        dataNascimentoTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gravarBtn = new javax.swing.JButton();
        sairBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 40, 210, 16);

        jLabel2.setText("Raça");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 220, 16);

        nomeAnimalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAnimalTxtActionPerformed(evt);
            }
        });
        getContentPane().add(nomeAnimalTxt);
        nomeAnimalTxt.setBounds(30, 60, 220, 22);
        getContentPane().add(racaAnimalTxt);
        racaAnimalTxt.setBounds(30, 110, 220, 22);

        jLabel3.setText("Especie");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 140, 210, 16);
        getContentPane().add(especieAnimalTxt);
        especieAnimalTxt.setBounds(30, 160, 220, 22);
        getContentPane().add(dataNascimentoTxt);
        dataNascimentoTxt.setBounds(30, 210, 220, 22);

        jLabel4.setText("Data de nascimento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 190, 210, 16);

        gravarBtn.setText("Gravar");
        getContentPane().add(gravarBtn);
        gravarBtn.setBounds(30, 250, 90, 22);

        sairBtn.setText("Sair");
        sairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sairBtn);
        sairBtn.setBounds(290, 330, 80, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeAnimalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAnimalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAnimalTxtActionPerformed

    private void sairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBtnActionPerformed
        this.dispose();
        PrincipalGUI telaPrincipal = new PrincipalGUI();
    }//GEN-LAST:event_sairBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimaisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimaisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimaisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimaisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimaisGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dataNascimentoTxt;
    private javax.swing.JTextField especieAnimalTxt;
    private javax.swing.JButton gravarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomeAnimalTxt;
    private javax.swing.JTextField racaAnimalTxt;
    private javax.swing.JButton sairBtn;
    // End of variables declaration//GEN-END:variables
}
