/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ClienteDAO;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import model.Clientes;

/**
 *
 * @author LABORATÓRIO
 */
public class ClientesGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientesGUI
     */
    public ClientesGUI() {
        initComponents();
        this.setVisible(true);
        this.setSize(900, 700);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
        this.setTitle("Clientes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFCpf = new javax.swing.JTextField();
        jTFTelefone = new javax.swing.JTextField();
        jTFEmail = new javax.swing.JTextField();
        jBTGravar = new javax.swing.JButton();
        jBTSair = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTFDataNascimento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxClientes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jBtAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 50, 270, 17);

        jLabel2.setText("CPF");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 50, 90, 17);

        jLabel3.setText("Telefone");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 50, 100, 17);

        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 100, 270, 17);
        getContentPane().add(jTFNome);
        jTFNome.setBounds(40, 70, 240, 23);
        getContentPane().add(jTFCpf);
        jTFCpf.setBounds(510, 70, 190, 23);
        getContentPane().add(jTFTelefone);
        jTFTelefone.setBounds(300, 70, 190, 23);
        getContentPane().add(jTFEmail);
        jTFEmail.setBounds(40, 120, 290, 23);

        jBTGravar.setText("Salvar");
        jBTGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTGravarActionPerformed(evt);
            }
        });
        getContentPane().add(jBTGravar);
        jBTGravar.setBounds(610, 120, 90, 20);

        jBTSair.setText("Voltar");
        jBTSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSairActionPerformed(evt);
            }
        });
        getContentPane().add(jBTSair);
        jBTSair.setBounds(20, 640, 80, 20);

        jLabel5.setText("Data nascimento");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 100, 160, 17);
        getContentPane().add(jTFDataNascimento);
        jTFDataNascimento.setBounds(340, 120, 190, 23);

        jLabel6.setText("Atualizar Cliente");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 210, 220, 17);

        jComboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecione--" }));
        jComboBoxClientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxClientesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxClientesFocusLost(evt);
            }
        });
        jComboBoxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxClientes);
        jComboBoxClientes.setBounds(270, 260, 310, 23);

        jLabel7.setText("Adicionar cliente");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 20, 190, 17);

        jBtAtualizar.setText("Atualizar");
        jBtAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtAtualizar);
        jBtAtualizar.setBounds(370, 330, 100, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSairActionPerformed
        this.dispose();
        PrincipalGUI telaPrincipal = new PrincipalGUI();
    }//GEN-LAST:event_jBTSairActionPerformed

    private void jBTGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTGravarActionPerformed
        String nome = jTFNome.getText().toString().trim();
        String email = jTFEmail.getText().toString().trim();
        String telefone = jTFTelefone.getText().toString().trim();
        String dataNascimento = jTFDataNascimento.getText().toString().trim();
        String cpf = jTFCpf.getText().toString().trim();
        
        Clientes cliente = new Clientes();
        cliente.setNome(nome);
        cliente.setEmail(email);
        cliente.setTelefone(telefone);
        cliente.setDataNascimento(dataNascimento);
        cliente.setCpf(cpf);
        
        new ClienteDAO().inserirCliente(cliente);
    }//GEN-LAST:event_jBTGravarActionPerformed

    private Integer Conversao(String palavra){
        Pattern pattern = Pattern.compile("^(\\d+),\\s*.*$");
        Matcher matcher = pattern.matcher(palavra);
        
        if (matcher.find()) {
        String idString = matcher.group(1);
        Integer id = Integer.parseInt(idString);
        return id;
    }
        return null;
    } 

   
    private Clientes clienteSelecionado;
    
    private void jComboBoxClientesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxClientesFocusGained
        
            List<Clientes> clienteArray = new ClienteDAO().buscarTodosClientes();
            for (Clientes cliente : clienteArray){           
                jComboBoxClientes.addItem(cliente.toString());  
            }                 

    }//GEN-LAST:event_jComboBoxClientesFocusGained

    private void jBtAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAtualizarActionPerformed

        String nome = jTFNome.getText().toString().trim();
        String email = jTFEmail.getText().toString().trim();
        String telefone = jTFTelefone.getText().toString().trim();
        String dataNascimento = jTFDataNascimento.getText().toString().trim();
        String cpf = jTFCpf.getText().toString().trim();
        
        
        Clientes cliente = new Clientes();
        cliente.setNome(nome);
        cliente.setEmail(email);
        cliente.setTelefone(telefone);
        cliente.setDataNascimento(dataNascimento);
        cliente.setCpf(cpf);
        cliente.setId(clienteSelecionado.getId());
        
        new ClienteDAO().alterarCliente(cliente);
        
        
    }//GEN-LAST:event_jBtAtualizarActionPerformed

    private void jComboBoxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClientesActionPerformed
        Integer idCliente = Conversao(jComboBoxClientes.getSelectedItem().toString());
        Clientes cliente = new ClienteDAO().buscarPorId(idCliente);
        clienteSelecionado = cliente;  
        
        jTFNome.setText(clienteSelecionado.getNome());
        jTFCpf.setText(clienteSelecionado.getCpf());
        jTFDataNascimento.setText(clienteSelecionado.getDataNascimento());
        jTFEmail.setText(clienteSelecionado.getEmail());
        jTFTelefone.setText(clienteSelecionado.getTelefone());
        
        jBTGravar.setEnabled(false);
            
    }//GEN-LAST:event_jComboBoxClientesActionPerformed

    private void jComboBoxClientesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxClientesFocusLost
       
    }//GEN-LAST:event_jComboBoxClientesFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTGravar;
    private javax.swing.JButton jBTSair;
    private javax.swing.JButton jBtAtualizar;
    private javax.swing.JComboBox<String> jComboBoxClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTFCpf;
    private javax.swing.JTextField jTFDataNascimento;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFTelefone;
    // End of variables declaration//GEN-END:variables
}
